### ISSUE TITLE
Nachkommastellenfehler beim Speichern

### ISSUE THREAD

**Issue by larsweiler** [lutoma/shortdiary#124]
Schickes, neues Design! :) Beim Speichern erhalte ich einen Fehler auf Höhe des Bereichs zum Hinzufügen von Bildern.

> Stelle sicher, dass es nicht mehr als 12 Nachkommastellen lang ist.

Habe einen neuen Eintrag angelegt, einen Text geschrieben, das Datum auf gestern gewechselt und noch die Mood etwas verändert. Der Fehler ließ sich wiederholen.

**Comment by larsweiler** [comment]
Noch etwas mehr getestet. Der Fehler gehört zur Location. Wenn ich die Eintragung der Location im Browser unterbinde, kann der Eintrag gespeichert werden.

**Comment by lutoma** [comment]
Danke für den Hinweis. Das Problem hatte ich schonmal gefunden und gefixt, aber scheinbar mit Flüchtigkeitsfehler... Nach e04e4ce sollte das wirklich passen.
