### ISSUE TITLE
Sign in not possible

### ISSUE THREAD

**Issue by larsweiler** [lutoma/shortdiary#125]
I had to sign in into my account again, but my unchanged credentials are not working any more. The error message is `Unable to login with provided credentials.` Instead of my username I also tried the email address, with no luck.

I did not change my password, but I changed the authenticator from SMS to TOTP between the last login and today's attempt.

Unfortunately I cannot find a "reset my password" procedure.

**Comment by larsweiler** [comment]
Login works again and the TOTP-request appears. I did not change anything.

**Comment by lutoma** [comment]
Only saw this issue just now. The Docker container for the staging environment was wrongly auto-started due to a faulty restart policy and started listening on the API endpoints instead of the production one. Hence the invalid login messages, since production logins don't work in the staging DB.
