### ISSUE TITLE
Wrong order of months

### ISSUE THREAD

**Issue by larsweiler** [lutoma/shortdiary#129]
With the start of November, the order of months are a bit messed up. October still comes first and then November. So, for the most recent entries, one has to scroll down in the Dashboard. Attached is a screenshot from the side of the Dashboard.

<img width="134" alt="Bildschirmfoto 2021-11-03 um 08 16 57" src="https://user-images.githubusercontent.com/790576/140022228-c1f0b9a5-03be-4ff2-a87b-b68d9918e167.png">

**Comment by larsweiler** [comment]
I think, that the function in https://github.com/lutoma/shortdiary/blob/147262209649e2afd892e020abbf82910a36dbeb/frontend/components/PostTimeline.vue#L178 needs a sorting algorithm. Currently it seems, that it works in the month order 10 11 12 01 02 03 etc as seen in the screenshot of all months in 2020.

<img width="134" alt="Bildschirmfoto 2021-11-03 um 08 40 47" src="https://user-images.githubusercontent.com/790576/140023994-b09089b9-2402-4e9b-9a0f-b8f781bca54d.png">

**Comment by lutoma** [comment]
Thanks for pointing this out! I'll see if I can fix it in the next few days.

**Comment by Monikae** [comment]
Now the posts on the left are sorted correctly \o/, only the months on the right are still sorted incorrectly.

**Comment by Monikae** [comment]
Now it say March, March, January
