### ISSUE TITLE
SSL problems with mobile iOS browsers

### ISSUE THREAD

**Issue by larsweiler** [lutoma/shortdiary#147]
Currently I have a problem with mobile iOS browsers (both, Safari and Chrome) on an iPhone and iPad stating some SSL errors after logging in to the page and loading the dashboard. Unfortunately I can’t find out the issue with the limited browser. From time to time the dashboard loads, but it shows the SSL error on the next refresh or sometime later.

I already deleted cookies and website data, switched off Adblocker and used the private browsing mode.

![8AF05796-1B3D-4D08-BB4E-A631E8CAEE4F](https://user-images.githubusercontent.com/790576/216773639-0de2bb8e-a2ed-48b9-9899-d3e327896a6b.png)
![5B3D0E49-0637-49D0-84D1-953780391610](https://user-images.githubusercontent.com/790576/216773642-501328f8-05ae-4b05-92af-51c5d0eb84dc.png)

**Comment by larsweiler** [comment]
With Firefox I get the Error “NSURLErrorDomain”. Probably that helps more.

**Comment by larsweiler** [comment]
For the past 3 days I had no problems any more. It seems like, this is fixed.

Closing for now.

**Comment by lutoma** [comment]
Probably an HTTP/3 issue with our load balancer that should now be fixed.
